name: pipeline

on:
  push:
    branches: [v*/develop]
  pull_request:
    branches: [v*/develop, master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:

  sanity-test-build:
    runs-on: RHEL8
    container: golang:1.16

    steps:
    - uses: actions/checkout@v2

    - name: Add Running Label
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.setLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [':arrows_counterclockwise:']
          })

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7

    - name: Check-linting-issues
      run: |
        if [ "$(gofmt -l . | wc -l)"  -gt 0 ]; then exit 1; fi

    - name: Run-unit-tests
      id: coverage-percent
      shell: bash
      run: |
        make test
        value=`go tool cover -func cover.out | grep total | awk '{print $3}'`
        echo "::set-output name=coverage::$value"
        echo $value

    - name: Add Coverage Label
      uses: actions/github-script@v2
      with:
       github-token: ${{secrets.GITHUB_TOKEN}}
       script: |
         github.issues.setLabels({
           issue_number: context.issue.number,
           owner: context.repo.owner,
           repo: context.repo.repo,
           labels: ['COV: ${{steps.coverage-percent.outputs.coverage}}']
         })
         
    - name: Build-cms
      run: make cms

    - name: Build-authservice
      run: make authservice

    - name: Build-hvs
      run: make hvs

    - name: Build-ihub
      run: make ihub

    - name: Build-wpm
      run: make wpm

    - name: Build-wls
      run: make wls

    - name: Build-kbs
      run: make kbs

  docker-push:
    if: github.event_name == 'push'
    needs: [ sanity-test-build ]
    runs-on: RHEL8
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: localhost,127.0.0.1,0.0.0.0
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7

    - name: Build-cms-docker
      run: |
        make cms-docker
        docker push `docker images | grep cms | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-authservice-docker
      run: |
        make authservice-docker
        docker push `docker images | grep authservice | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-hvs-docker
      run: |
        make hvs-docker
        docker push `docker images | grep hvs | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-ihub-docker
      run: |
        make ihub-docker
        docker push `docker images | grep ihub | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-wls-docker
      run: |
        make wls-docker
        docker push `docker images | grep wls | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-kbs-docker
      run: |
        make kbs-docker
        docker push `docker images | grep kbs | awk '{print $1":"$2}' | awk 'NR==1'`
