name: dockerpush

on:
  push:
    branches: [ v*/develop, master ]

jobs:
  docker-push:
    runs-on: RHEL8

    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: localhost,127.0.0.1,0.0.0.0
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.16.7
                 
      - name: Build-cms-docker
        run: |
          make cms-docker
          docker push `docker images | grep cms | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-authservice-docker
        run: |
          make authservice-docker
          docker push `docker images | grep authservice | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-hvs-docker
        run: |
          make hvs-docker
          docker push `docker images | grep hvs | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-ihub-docker
        run: |
          make ihub-docker
          docker push `docker images | grep ihub | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-wls-docker
        run: |
          make wls-docker
          docker push `docker images | grep wls | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-kbs-docker
        run: |
          make kbs-docker
          docker push `docker images | grep kbs | awk '{print $1":"$2}' | awk 'NR==1'`
          
      - name: Build-tagent-docker
        run: |
          make tagent-docker
          docker push `docker images | grep tagent | awk '{print $1":"$2}' | awk 'NR==1'`
          
      - name: Build-wlagent-docker
        run: |
          make wlagent-docker
          docker push `docker images | grep wlagent | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-admission-controller-docker
        run: |
          make admission-controller-docker
          docker push `docker images | grep admission-controller | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-k8s-controller-docker
        run: |
          make isecl-k8s-controller-docker
          docker push `docker images | grep isecl-k8s-controller | awk '{print $1":"$2}' | awk 'NR==1'`

      - name: Build-k8s-scheduler-docker
        run: |
          make isecl-k8s-scheduler-docker
          docker push `docker images | grep isecl-k8s-scheduler | awk '{print $1":"$2}' | awk 'NR==1'`
