name: dockerpush

on:
  push:
    branches: [ v*/develop, master ]

jobs:
  docker-push:
    runs-on: RHEL8

    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: localhost,127.0.0.1,0.0.0.0
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.16.7
                 
      - name: Build-cms-docker
        run: |
          make cms-docker-push

      - name: Build-authservice-docker
        run: |
          make authservice-docker-push

      - name: Build-hvs-docker
        run: |
          make hvs-docker-push

      - name: Build-ihub-docker
        run: |
          make ihub-docker-push

      - name: Build-wls-docker
        run: |
          make wls-docker-push

      - name: Build-kbs-docker
        run: |
          make kbs-docker-push

      - name: Build-tagent-docker
        run: |
          make tagent-docker-push

      - name: Build-wlagent-docker
        run: |
          make wlagent-docker-push

      - name: Build-admission-controller-docker
        run: |
          make admission-controller-docker-push

      - name: Build-k8s-controller-docker
        run: |
          make isecl-k8s-controller-docker-push

      - name: Build-k8s-scheduler-docker
        run: |
          make isecl-k8s-scheduler-docker-push