name: build

on:
  push:
    branches: [v*/develop]
  pull_request:
    branches: [v*/develop, master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:

  build:
    runs-on: RHEL8
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: localhost,127.0.0.1,0.0.0.0
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7

    - name: Build-cms
      run: make cms

    - name: Build-cms-docker
      run: |
        make cms-docker
        docker push `docker images | grep cms | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-authservice
      run: make authservice

    - name: Build-authservice-docker
      run: |
        make authservice-docker
        docker push `docker images | grep authservice | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-hvs
      run: make hvs

    - name: Build-hvs-docker
      run: |
        make hvs-docker
        docker push `docker images | grep hvs | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-ihub
      run: make ihub

    - name: Build-ihub-docker
      run: |
        make ihub-docker
        docker push `docker images | grep ihub | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-wpm
      run: make wpm

    - name: Build-wls
      run: make wls

    - name: Build-wls-docker
      run: |
        make wls-docker
        docker push `docker images | grep wls | awk '{print $1":"$2}' | awk 'NR==1'`

    - name: Build-kbs
      run: make kbs

    - name: Build-kbs-docker
      run: |
        make kbs-docker
        docker push `docker images | grep kbs | awk '{print $1":"$2}' | awk 'NR==1'`
